import requests
import random
import string
from datetime import datetime

BASE = "http://127.0.0.1:8000/api"


def rand(n=6):
    return ''.join(random.choice(string.ascii_lowercase) for _ in range(n))


def req(method, path, token=None, **kwargs):
    h = kwargs.pop("headers", {})
    if token:
        h["Authorization"] = f"Bearer {token}"
    try:
        r = requests.request(method, BASE + path, headers=h, timeout=20, **kwargs)
        return r.status_code, r.json() if r.text else {}
    except Exception as e:
        return 0, {"error": str(e)}


def ensure_user(email, name, password="demo123"):
    code, data = req("POST", "/auth/signup", json={"email": email, "name": name, "password": password})
    if code in (200, 201):
        uid = data.get("user_id")
        vcode = data.get("verification_code")
        if uid and vcode:
            req("POST", f"/auth/verify?user_id={uid}&code={vcode}")
    # login anyway (works if user already exists)
    lcode, ldata = req("POST", "/auth/login", json={"email": email, "password": password})
    return lcode, ldata.get("access_token"), ldata


def main():
    summary = {}

    # base seed
    code, data = req("POST", "/seed")
    summary["seed"] = (code, data)

    # admin login from seed
    code, login = req("POST", "/auth/login", json={"email": "admin@petsy.com", "password": "admin123"})
    admin_token = login.get("access_token") if code == 200 else None
    summary["admin_login"] = code

    # extra demo users
    users = []
    for i in range(1, 4):
        email = f"demo{i}@petsy.com"
        code, token, _ = ensure_user(email, f"Demo User {i}", "demo123")
        users.append((email, token, code))
    summary["users"] = [(u[0], u[2]) for u in users]

    actor_token = users[0][1] or admin_token
    other_token = users[1][1] or admin_token

    # pets
    for i in range(3):
        req("POST", "/pets", token=actor_token, json={
            "name": f"SamplePet{rand(4)}",
            "species": random.choice(["cat", "dog", "bird"]),
            "breed": "Mixed",
            "age": f"{random.randint(1,5)} years",
            "gender": random.choice(["male", "female"]),
            "location": "Damascus",
            "description": "Auto-generated sample pet",
            "vaccinated": bool(i % 2),
            "status": random.choice(["for_adoption", "for_sale"]),
            "price": random.randint(50, 250),
        })

    # marketplace listings
    for i in range(4):
        req("POST", "/marketplace/listings", token=actor_token, json={
            "title": f"Sample Listing {i+1} {rand(3)}",
            "description": "Generated listing for UI testing",
            "category": random.choice(["pets", "accessories", "services"]),
            "price": round(random.uniform(10, 300), 2),
            "location": random.choice(["Damascus", "Aleppo", "Homs"]),
            "pet_type": random.choice(["dog", "cat", "all"]),
            "condition": random.choice(["new", "used"]),
        })

    # community posts
    for i in range(4):
        req("POST", "/community", token=actor_token, json={
            "content": f"Sample community post {i+1} at {datetime.utcnow().isoformat()}",
            "post_type": random.choice(["general", "advice", "adoption", "lost_found"]),
            "location": random.choice(["Damascus", "Aleppo"]),
        })

    # lost-found
    for i in range(2):
        req("POST", "/lost-found", token=actor_token, json={
            "type": random.choice(["lost", "found"]),
            "pet_name": f"LF-{rand(4)}",
            "species": random.choice(["cat", "dog"]),
            "breed": "Mixed",
            "description": "Autogenerated lost/found report",
            "location": "Damascus",
            "contact_phone": "+963900000000",
            "status": "active",
        })

    # role requests
    for role in ["vet", "market_owner", "care_clinic"]:
        req("POST", "/role-requests", token=actor_token, json={"target_role": role, "reason": f"Sample request for {role}"})

    # friends + chat
    if users[1][1] and users[0][1]:
        code, me = req("GET", "/auth/me", token=users[1][1])
        uid2 = me.get("id") if code == 200 else None
        if uid2:
            req("POST", "/friends/requests", token=users[0][1], json={"target_user_id": uid2, "message": "Sample friend request"})
            code, reqs = req("GET", "/friends/requests", token=users[1][1])
            incoming = (reqs.get("incoming") or reqs.get("requests") or []) if isinstance(reqs, dict) else []
            if incoming:
                req_id = incoming[0].get("id")
                if req_id:
                    req("PUT", f"/friends/requests/{req_id}", token=users[1][1], json={"action": "accept"})
            # direct chat
            code, me1 = req("GET", "/auth/me", token=users[0][1])
            uid1 = me1.get("id") if code == 200 else None
            if uid1:
                code, conv = req("POST", "/conversations", token=users[1][1], json={"other_user_id": uid1, "initial_message": "Hello from sample data"})
                cid = conv.get("id") or (conv.get("data") or {}).get("id")
                if cid:
                    req("POST", f"/conversations/{cid}/messages", token=users[0][1], params={"content": "Reply sample message"})

    # appointments from vets
    code, vets = req("GET", "/vets", token=actor_token)
    vet_list = vets if isinstance(vets, list) else vets.get("items") if isinstance(vets, dict) else []
    if vet_list:
        vid = vet_list[0].get("id")
        if vid:
            req("POST", "/appointments", token=actor_token, json={
                "vet_id": vid,
                "pet_name": "SamplePet",
                "date": "2026-02-20",
                "time": "10:30",
                "reason": "Routine checkup sample",
                "notes": "Generated for UI testing"
            })

    # orders from products
    code, prods = req("GET", "/products", token=actor_token)
    plist = prods if isinstance(prods, list) else prods.get("items") if isinstance(prods, dict) else []
    if plist:
        items = []
        total = 0
        for p in plist[:2]:
            q = 1
            price = float(p.get("price", 0) or 0)
            total += price * q
            items.append({"product_id": p.get("id"), "name": p.get("name"), "price": price, "quantity": q, "image": p.get("image")})
        req("POST", "/orders", token=actor_token, json={
            "items": items,
            "total": total,
            "shipping_address": "Sample Street 12",
            "shipping_city": "Damascus",
            "shipping_phone": "+963900000000",
            "payment_method": "cash_on_delivery",
            "notes": "Generated sample order"
        })

    print("DONE")
    print(summary)


if __name__ == "__main__":
    main()
